# For documentation build info, see docs/DOCS_README.md.
name: ⛓️ Test static build (pull request)
on:
  pull_request:
    paths: [docs/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS and npm
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install yarn using npm
        run: npm install -g yarn
      - name: Setup NodeJS with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: docs/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Build the application
        run: yarn build

